spring.application.name=demo
server.port=8085
#Variables agregadas para funcionamiento de jsp y jstl
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Configuracion de recursos estaticos
spring.web.resources.static-locations=classpath:/webapp/

#logging.level.org.springframework=DEBUG
#logging.level.org.apache.catalina=DEBUG

# Ejecutar scripts al iniciar
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.schema-locations=classpath:schema.sql

# H2 Configuration
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


# Habilita la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desactiva JPA/Hibernate
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Configuracion del pool de conexiones (HikariCP)
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000


saludo.bienvenida=Bienvenido

